rewrite css styles to jumbotron
coderdave/myrecipes pull request #12
Opened 2022-06-01 21:13 UTC by josemorin

2022-06-01 21:15 UTC, coderdave requested changes

2022-06-01 21:15 UTC, coderdave commented on app/assets/stylesheets/custom.css.scss
> +.costum_jumbotron{
rename to `custom_jumbotron`

2022-06-01 21:32 UTC, AlexRS90 requested changes
Hey @josemorin 
Good job so far, only check the class name in the below comment ⬇️

2022-06-01 21:32 UTC, AlexRS90 commented on app/views/pages/home.html.erb
> +  <p><%= link_to "Sign up for the app", signup_path, class: "btn btn-danger btn-lg costum_jumbotron" %></p>
Hi @josemorin 
I think you need to change the name of the class here as well

2022-06-01 21:58 UTC, AlexRS90 approved these changes

2022-06-02 14:00 UTC, jm4rt1n3z approved these changes

2022-06-02 19:26 UTC, merged